<?php

namespace app\controllers;

use app\models\Clip;
use app\models\Credit;
use app\models\Genre;
use app\models\Item;
use app\models\ItemGenre;
use app\models\ItemProvider;
use app\models\Person;
use app\models\Provider;
use app\models\UrlLink;
use Yii;
use yii\base\Exception;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\helpers\Json;
use yii\web\Controller;
use yii\web\HttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\widgets\LinkPager;

// id jw => id topflix
const provider_id = [
    8   => 2, //netflix
    118 => 4, //hbo
    149 => 1, //mvs
    119 => 3, // prime video
];

class SiteController extends Controller
{
    /**
     * @param $action
     * @return bool
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        ini_set('memory_limit', '1024M');
        ini_set('max_execution_time', 0);

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionSearch()
    {
        $query = Item::find()
            ->where(['not',['imdb_score'=>true]])
            ->andWhere(['not',['poster' => null]]);
        $count_query = clone $query;
        $pages = new Pagination(['totalCount' => $count_query->count()]);
        $models = $query
            ->offset($pages->offset)
            ->limit($pages->limit)
            ->orderBy("imdb_score DESC")
            ->all();

        return $this->render('search.twig', [
            'items' => $models,
            'pages' => $pages,
        ]);
    }

    /**
     * @param $id
     * @return string
     * @throws \Exception
     */
    public function actionItem($id)
    {
        if (empty($id)) {
            throw new NotFoundHttpException("Missing required parameter.");
        }

        /** @var Item $item */
        $item = Item::findOne($id);

        if (empty($item)) {
            throw new NotFoundHttpException("Item not found");
        }

        return $this->render('item.twig', [
            'item' => $item
        ]);
    }

}
